// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load secrets from `.env.local` (git-ignored). Next.js already loads
// `.env.local` for the running app, so this keeps Prisma CLI and the app on a
// single source of truth. The default Prisma-generated `.env` only held a
// localhost placeholder and is intentionally not loaded here.
dotenv.config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // `--conditions=react-server` is required: plan-service.ts imports
    // `server-only`, whose package export map throws outside a React Server
    // Component context. Without it `prisma db seed` fails before running.
    seed: "tsx --conditions=react-server prisma/seed.ts",
  },
  datasource: {
    // Migrations must use the direct connection (DIRECT_URL) — Supabase's
    // pooled pgbouncer connection (DATABASE_URL) does not reliably support
    // schema migrations. Runtime queries use DATABASE_URL via the driver
    // adapter in src/lib/prisma.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
