import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  BadgeCheck,
  Bell,
  Boxes,
  Building2,
  CalendarClock,
  CalendarDays,
  ChartColumnBig,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleHelp,
  CircleUser,
  Cloud,
  CloudOff,
  Copy,
  CreditCard,
  Crown,
  Eye,
  EyeOff,
  FileSpreadsheet,
  FileText,
  Globe,
  Grid2x2,
  Handshake,
  Hash,
  Hourglass,
  House,
  Inbox,
  IndianRupee,
  Info,
  KeyRound,
  Languages,
  LayoutDashboard,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Menu,
  Monitor,
  NotebookPen,
  Package,
  Percent,
  Phone,
  Plus,
  Receipt,
  RefreshCw,
  Rocket,
  RotateCcw,
  Save,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Star,
  Store,
  Tags,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Type,
  Undo2,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  Warehouse,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * The single source of truth for every icon glyph in the app.
 *
 * Material Symbols used to be pulled from a Google Fonts `@import` and drawn
 * as ligature text (`<span class="material-symbols-outlined">dashboard</span>`).
 * That made the glyph depend on a webfont arriving over the network, so any
 * cold or hard-refreshed paint could show the raw ligature name as text.
 * Icons are now inline SVG emitted by React: present in the first HTML
 * response, no font download, no hydration, no layout shift.
 *
 * IconName is derived from this map, so a name used in code that is not mapped
 * here is a type error rather than a runtime surprise.
 */
const ICONS = {
  account_balance: Wallet,
  account_balance_wallet: Wallet,
  add: Plus,
  annual: CalendarDays,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  assessment: ChartColumnBig,
  auto: Zap,
  autorenew: RefreshCw,
  badge: Award,
  bar_chart: ChartColumnBig,
  call: Phone,
  calendar_month: CalendarDays,
  cancel: X,
  card_membership: CreditCard,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud: Cloud,
  cloud_off: CloudOff,
  custom: Sparkles,
  dashboard: LayoutDashboard,
  degraded: TriangleAlert,
  delete: Trash2,
  description: FileText,
  domain: Globe,
  done_all: CheckCircle2,
  down: ChevronDown,
  duplicate: Copy,
  edit_note: NotebookPen,
  error: CircleAlert,
  error_outline: CircleAlert,
  estimate: FileSpreadsheet,
  event: CalendarDays,
  event_repeat: RefreshCw,
  expand_more: ChevronDown,
  failed: TriangleAlert,
  grace: Hourglass,
  grid_view: Grid2x2,
  group: Users,
  group_add: UserPlus,
  groups: UsersRound,
  handshake: Handshake,
  help: CircleHelp,
  home: House,
  inbox: Inbox,
  insights: TrendingUp,
  info: Info,
  interstate: Truck,
  intrastate: Truck,
  inventory_2: Boxes,
  key: KeyRound,
  language: Languages,
  limit: Hourglass,
  local_shipping: Truck,
  location_city: Building2,
  location_on: MapPin,
  lock: Lock,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  map: Map,
  menu: Menu,
  missing: TriangleAlert,
  monitoring: Monitor,
  month: CalendarDays,
  monthly: CalendarDays,
  notifications: Bell,
  numbers: Hash,
  ok: Check,
  password: KeyRound,
  payments: IndianRupee,
  payroll: Wallet,
  percent: Percent,
  person: CircleUser,
  person_add: UserPlus,
  picture_as_pdf: FileText,
  pin_drop: MapPin,
  present: Star,
  preview: Eye,
  product: Package,
  progress_activity: LoaderCircle,
  public: Globe,
  quotation: FileText,
  receipt: Receipt,
  receipt_long: Receipt,
  refresh: RefreshCw,
  request_quote: FileText,
  rocket_launch: Rocket,
  save: Save,
  schedule: CalendarClock,
  search: Search,
  seat: UserRound,
  seats: Users,
  sell: Store,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  shopping_cart: ShoppingCart,
  shopping_cart_checkout: ShoppingCart,
  smooth: Sparkles,
  south: ArrowDown,
  storefront: Store,
  success: CheckCircle2,
  supplier: Warehouse,
  suppliers: Warehouse,
  tag: Tags,
  text: Type,
  undo: Undo2,
  up: ArrowUp,
  update: RotateCcw,
  verified: BadgeCheck,
  verified_user: BadgeCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: TriangleAlert,
  workspace_premium: Crown,
  year: CalendarDays,
  yearly: CalendarDays,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

type IconProps = {
  /** Registered icon name. */
  name: IconName;
  className?: string;
} & Omit<React.SVGProps<SVGSVGElement>, "ref" | "children" | "name">;

/**
 * Renders an icon as an inline SVG sized in `em` and coloured by `currentColor`.
 *
 * Because the box is `1em`, the `text-[20px]`-style size utilities and the
 * `text-primary` / `text-secondary` colour utilities already present at call
 * sites keep working untouched, so adopting this component does not move any
 * layout. `animate-spin` also still applies, and the reduced-motion rule in
 * globals.css still finds the element.
 */
export function Icon({ name, className, ...rest }: IconProps) {
  const Glyph = ICONS[name];
  if (!Glyph) {
    if (process.env.NODE_ENV !== "production") {
      console.warn(`[Icon] unknown icon name "${name}"`);
    }
    return null;
  }
  return <Glyph aria-hidden="true" focusable="false" width="1em" height="1em" className={className} {...rest} />;
}
